"""
Utility helpers for the Lex Amoris framework.
"""

import textwrap
from datetime import datetime, timezone


def format_reflection(agent_name: str, situation: str, guidance: str) -> str:
    """Wrap a reflection into a structured, readable string.

    Parameters
    ----------
    agent_name : str
        The name of the reflecting agent.
    situation : str
        The original situation description.
    guidance : str
        The guidance generated by the framework.

    Returns
    -------
    str
        A formatted reflection block.
    """
    timestamp = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    header = f"=== Reflection by {agent_name} ({timestamp}) ==="
    situation_block = textwrap.fill(
        f"Situation: {situation}", width=72, subsequent_indent="           "
    )
    separator = "-" * len(header)
    return "\n".join([header, situation_block, separator, guidance])


def list_principles_summary(principles) -> str:
    """Return a compact summary of a list of principles.

    Parameters
    ----------
    principles : list[Principle]
        The principles to summarise.

    Returns
    -------
    str
        A numbered list of principle names and descriptions.
    """
    if not principles:
        return "No principles to display."
    lines = []
    for i, p in enumerate(principles, start=1):
        lines.append(f"{i:2d}. {p.name}: {p.description}")
    return "\n".join(lines)
